### ISSUE TITLE
Consistently getting "git am failed, likely because of an in-progress 'git am' or 'git rebase'"

### ISSUE THREAD

**Issue by lizziemac** [tisonkun/gh-cherry-pick#2]
Hi there! I'd like to use your `gh` extension, but I can't seem to get past the below.  Am I missing anything? Thanks!

```sh
$ DRY_RUN=1 UPSTREAM_REMOTE='origin' GITHUB_USER='<org>' gh cherry-pick origin/<branch> <pr> 

+++ Updating remotes...
Fetching origin
Fetching origin
+++ Creating local branch automated-cherry-pick-of-#104-origin-22.03.10-release-1647630777
Branch 'automated-cherry-pick-of-#104-origin-22.03.10-release-1647630777' set up to track remote branch '22.03.10-release' from 'origin'.
Switched to a new branch 'automated-cherry-pick-of-#104-origin-22.03.10-release-1647630777'
+++ Downloading patch to /var/folders/bc/m16t7t31117_scz1zv30bt600000gq/T/tmp.BHw5MiMX/104.patch (in case you need to do this again)

+++ About to attempt cherry pick of PR. To reattempt:
  $ git am -3 /var/folders/bc/m16t7t31117_scz1zv30bt600000gq/T/tmp.BHw5MiMX/104.patch

Patch format detection failed.
!!! git am failed, likely because of an in-progress 'git am' or 'git rebase'

+++ Aborting in-progress git am.
```

I've verified that no `am` or `rebase` operations are in progress, and still get this every time, even when I start on the main branch with no changes:
```sh
$ git status
On branch automated-cherry-pick-of-#<pr>-origin-<branch>-1647630777
Your branch is up to date with 'origin/<branch>'.

nothing to commit, working tree clean
$ git am  --abort
fatal: Resolve operation not in progress, we are not resuming.
$ git rebase --abort
fatal: No rebase in progress?
```

**Comment by tisonkun** [comment]
If it's the first time you run with this extension, and there is an in-progress `am`, on cleanup stage it will abort so that you don't see the state in-progress later.

What's the output you run `git am -3 /var/folders/bc/m16t7t31117_scz1zv30bt600000gq/T/tmp.BHw5MiMX/104.patch` after the script failed? Or can you provide a reproducible repo and branch so that I can dig into it?

**Comment by tisonkun** [comment]
@lizziemac yes. That's possible your auth account doesn't have permission to access that pr you'd like o cherry pick.

You can run `gh auth status` to see whether it's the account with required permission.

**Comment by tisonkun** [comment]
I'll close this issue later as information delivered above. If it's not the case and there're other questions. Feel free to comment or reopen then.
